name: movie_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1 
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0
  go_router: ^6.0.9
  google_fonts: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  readmore: ^2.2.0
  shimmer: ^2.0.0
  stream_transform: ^2.1.0
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
